export function useAntenna() {
    const antenna = [
        { value:'Antena apilada', label:'Antena apilada'},
        { value:'Antena beverage', label:'Antena beverage'},
        { value:'Antena billboard', label:'Antena billboard'},
        { value:'Antena coaxial', label:'Antena coaxial'},
        { value:'Antena con reflector hiperbólico', label:'Antena con reflector hiperbólico'},
        { value:'Antena con reflector parabólico', label:'Antena con reflector parabólico'},
        { value:'Antena de cuadro', label:'Antena de cuadro'},
        { value:'Antena discono', label:'Antena discono'},
        { value:'Antena helicoidal con reflector', label:'Antena helicoidal con reflector'},
        { value:'Antena helicoidal con reflector lateral', label:'Antena helicoidal con reflector lateral'},
        { value:'Antena helicoidal sin reflector', label:'Antena helicoidal sin reflector'},
        { value:'Antena log-periódica', label:'Antena log-periódica'},
        { value:'Antena rómbica simple', label:'Antena rómbica simple'},
        { value:'Antena rómbica tipo cortina', label:'Antena rómbica tipo cortina'},
        { value:'Antena superturnstile', label:'Antena superturnstile'},
        { value:'Antena Tunipole', label:'Antena Tunipole'},
        { value:'Antena turnstile', label:'Antena turnstile'},
        { value:'Yagi con 1 elemento', label:'Yagi con 1 elemento'},
        { value:'Yagi con 10 elementos', label:'Yagi con 10 elementos'},
        { value:'Yagi con 11 elementos', label:'Yagi con 11 elementos'},
        { value:'Yagi con 12 elementos', label:'Yagi con 12 elementos'},
        { value:'Yagi con 13 elementos', label:'Yagi con 13 elementos'},
        { value:'Yagi con 14 elementos', label:'Yagi con 14 elementos'},
        { value:'Yagi con 15 elementos', label:'Yagi con 15 elementos'},
        { value:'Yagi con 16 elementos', label:'Yagi con 16 elementos'},
        { value:'Yagi con 18 elementos', label:'Yagi con 18 elementos'},
        { value:'Yagi con 3 elementos', label:'Yagi con 3 elementos'},
        { value:'Yagi con 4 elementos', label:'Yagi con 4 elementos'},
        { value:'Yagi con 5 elementos', label:'Yagi con 5 elementos'},
        { value:'Yagi con 6 elementos', label:'Yagi con 6 elementos'},
        { value:'Yagi con 7 elementos', label:'Yagi con 7 elementos'},
        { value:'Yagi con 8 elementos', label:'Yagi con 8 elementos'},
        { value:'Yagi con 9 elementos', label:'Yagi con 9 elementos'},
        { value:'Bibanda (VHF/UHF)', label:'Bibanda (VHF/UHF)'},
        { value:'Bocina', label:'Bocina'},
        { value:'Cable Coaxil', label:'Cable Coaxil'},
        { value:'Cable ranurado', label:'Cable ranurado'},
        { value:'Cámara con antena omnidireccional', label:'Cámara con antena omnidireccional'},
        { value:'Colineal', label:'Colineal'},
        { value:'Conjuntos de radiación longitudinal', label:'Conjuntos de radiación longitudinal'},
        { value:'Conjuntos de radiación transversal', label:'Conjuntos de radiación transversal'},
        { value:'Conjuntos lineales no uniformes', label:'Conjuntos lineales no uniformes'},
        { value:'Conjuntos lineales uniformes', label:'Conjuntos lineales uniformes'},
        { value:'Conjuntos planos', label:'Conjuntos planos'},
        { value:'Cortina de dipolos con reflector', label:'Cortina de dipolos con reflector'},
        { value:'Cortina de dipolos dobles con reflector', label:'Cortina de dipolos dobles con reflector'},
        { value:'Cortina de dipolos sin reflector', label:'Cortina de dipolos sin reflector'},
        { value:'Diedro', label:'Diedro'},
        { value:'Diedro con reflector', label:'Diedro con reflector'},
        { value:'Diedro doble', label:'Diedro doble'},
        { value:'Diedro simple', label:'Diedro simple'},
        { value:'Diedro sólido', label:'Diedro sólido'},
        { value:'Dipolo abierto', label:'Dipolo abierto'},
        { value:'Dipolo abierto con director', label:'Dipolo abierto con director'},
        { value:'Dipolo cerrado', label:'Dipolo cerrado'},
        { value:'Dipolo cerrado con director', label:'Dipolo cerrado con director'},
        { value:'Dipolo circular', label:'Dipolo circular'},
        { value:'Dipolo con reflector lateral', label:'Dipolo con reflector lateral'},
        { value:'Dipolo curvo', label:'Dipolo curvo'},
        { value:'Dipolo de cuarto de onda', label:'Dipolo de cuarto de onda'},
        { value:'Dipolo de cuarto de onda con reflector plano', label:'Dipolo de cuarto de onda con reflector plano'},
        { value:'Dipolo de media onda', label:'Dipolo de media onda'},
        { value:'Dipolo de media onda con reflector plano', label:'Dipolo de media onda con reflector plano'},
        { value:'Dipolo de onda completa con reflector plano', label:'Dipolo de onda completa con reflector plano'},
        { value:'Dipolo doblado de 2 elementos', label:'Dipolo doblado de 2 elementos'},
        { value:'Dipolo doblado de 3 elementos', label:'Dipolo doblado de 3 elementos'},
        { value:'Dipolos cruzados', label:'Dipolos cruzados'},
        { value:'Dipolos ortogonales', label:'Dipolos ortogonales'},
        { value:'Direccional con características conocidas (RJ81)', label:'Direccional con características conocidas (RJ81)'},
        { value:'Direccional con sectores de radiación limitada (RJ81)', label:'Direccional con sectores de radiación limitada (RJ81)'},
        { value:'Grillada', label:'Grillada'},
        { value:'Hilos radiantes', label:'Hilos radiantes'},
        { value:'J-POLE', label:'J-POLE'},
        { value:'Mástil irradiante aislado de tierra', label:'Mástil irradiante aislado de tierra'},
        { value:'Monoplo con plano de tierra', label:'Monoplo con plano de tierra'},
        { value:'Monopolo', label:'Monopolo'},
        { value:'Monopolo (doble 5/8) con plano a tierra', label:'Monopolo (doble 5/8) con plano a tierra'},
        { value:'Monopolo Aislado', label:'Monopolo Aislado'},
        { value:'Monopolo con base magnética', label:'Monopolo con base magnética'},
        { value:'Monopolo con carga al tope', label:'Monopolo con carga al tope'},
        { value:'Monopolo con plano a tierra', label:'Monopolo con plano a tierra'},
        { value:'Monopolo con plano de tierra a 45°', label:'Monopolo con plano de tierra a 45°'},
        { value:'Monopolo cónico', label:'Monopolo cónico'},
        { value:'Monopolo de cuatro hilos', label:'Monopolo de cuatro hilos'},
        { value:'Monopolo doblado', label:'Monopolo doblado'},
        { value:'Monopolo vertical', label:'Monopolo vertical'},
        { value:'Monopolo vertical con plano de tierra', label:'Monopolo vertical con plano de tierra'},
        { value:'Monopolo VHF tipo Ringo', label:'Monopolo VHF tipo Ringo'},
        { value:'Multibanda', label:'Multibanda'},
        { value:'No posee', label:'No posee'},
        { value:'No se observa', label:'No se observa'},
        { value:'No se pudo determinar', label:'No se pudo determinar'},
        { value:'Omnidireccional de carga terminal (RJ81)', label:'Omnidireccional de carga terminal (RJ81)'},
        { value:'Omnidireccional seccionada (RJ81)', label:'Omnidireccional seccionada (RJ81)'},
        { value:'Panel plano', label:'Panel plano'},
        { value:'Panel sectorial', label:'Panel sectorial'},
        { value:'Paneles de dipolos', label:'Paneles de dipolos'},
        { value:'Parabola', label:'Parabola'},
        { value:'Parábola con radomo', label:'Parábola con radomo'},
        { value:'Parabola grillada', label:'Parabola grillada'},
        { value:'Parabola sólida', label:'Parabola sólida'},
        { value:'Reflector pasivo', label:'Reflector pasivo'},
        { value:'Ringo Ranger (doble 5/8)', label:'Ringo Ranger (doble 5/8)'},
        { value:'Simple Omnidireccional (RJ81)', label:'Simple Omnidireccional (RJ81)'},
        { value:'Slot', label:'Slot'},
        { value:'Suma de dipolos', label:'Suma de dipolos'},
        { value:'V invertida', label:'V invertida'},
        { value:'Ver observaciones', label:'Ver observaciones'},
        {
            value:'---',
            label:'---'
        }]

    return { antenna }
}