export function useService() {
    const servicio = [
        { value: 'FM', label: 'FM'},
        { value: 'TV', label: 'TV'},
        { value: 'AM', label: 'AM'},
        { value: 'STVC', label: 'STVC'},
        { value: 'RPTTV', label: 'RPTTV'},
        { value: 'CCTVS', label: 'CCTVS'},
        { value: 'CCCAF', label: 'CCCAF'},
        { value: 'MCVHF', label: 'MCVHF'},
        { value: 'SEE', label: 'SEE'},
        { value: 'TPRS', label: 'TPRS'},
        { value: 'TXDAT', label: 'TXDAT'},
        { value: 'MCREM', label: 'MCREM'},
        { value: 'MCBO', label: 'MCBO'},
        { value: 'CCCTV', label: 'CCCTV'},
        { value: 'SAEMG', label: 'SAEMG'},
        { value: 'SCMA', label: 'SCMA'},
        { value: 'MXD', label: 'MXD'},
        { value: 'TPTV', label: 'TPTV'},
        { value: 'TPMTV', label: 'TPMTV'},
        { value: 'SFDVA', label: 'SFDVA'},
        { value: 'AISBT', label: 'AISBT'},
        { value: 'SBC', label: 'SBC'},
        { value: 'TCHF', label: 'TCHF'},
        { value: 'SRT', label: 'SRT'},
        { value: 'MEVHF', label: 'MEVHF'},
        { value: 'MVCHF', label: 'MVCHF'},
        { value: 'SMM', label: 'SMM'},
        { value: 'MCTEL', label: 'MCTEL'},
        { value: 'RTRAM', label: 'RTRAM'},
        { value: 'SBP', label: 'SBP'},
        { value: 'SRC', label: 'SRC'},
        { value: 'MXA', label: 'MXA'},
        { value: 'MCMED', label: 'MCMED'},
        { value: 'MCUHF', label: 'MCUHF'},
        { value: 'MCHVF', label: 'MCHVF'},
        { value: 'STM', label: 'STM'},
        { value: 'SRMC', label: 'SRMC'},
        { value: 'SRCE', label: 'SRCE'},
        { value: 'DBP', label: 'DBP'},
        { value: 'PCS', label: 'PCS'},
        { value: 'MMDS', label: 'MMDS'},
        { value: 'SAF', label: 'SAF'},
        { value: 'ACTV', label: 'ACTV'},
        { value: 'SMTV', label: 'SMTV'},
        { value: 'PCHF', label: 'PCHF'},
        { value: 'SAPAP', label: 'SAPAP'},
        { value: 'SRA', label: 'SRA'},
        { value: 'TVRU', label: 'TVRU'},
        { value: 'TEPR', label: 'TEPR'},
        { value: 'ARPAP', label: 'ARPAP'},
        { value: 'VHF', label: 'VHF'},
        { value: 'TPHF', label: 'TPHF'},
        { value: 'POE', label: 'POE'},
        { value: 'SMA', label: 'SMA'},
        { value: 'SCPE', label: 'SCPE'},
        { value: 'RA', label: 'RA'},
        { value: 'MCOOP', label: 'MCOOP'},
        { value: 'SAP', label: 'SAP'},
        { value: 'SAPB', label: 'SAPB'},
        { value: 'APL', label: 'APL'},
        { value: 'RPT', label: 'RPT'},
        { value: 'SDSA', label: 'SDSA'},
        { value: 'CPLD', label: 'CPLD'},
        { value: 'FX', label: 'FX'},
        { value: 'SIDUP', label: 'SIDUP'},
        { value: 'SMAR', label: 'SMAR'},    
        {
            value: '---',
            label: '---'
        }]

    return { servicio }
}