"""Add NIR table

Revision ID: 9087f1c101fa
Revises: 52ec0b684069
Create Date: 2024-06-09 22:40:35.980486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9087f1c101fa'
down_revision = '52ec0b684069'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('No')
    with op.batch_alter_table('NonIonizingRadiation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expediente', sa.String(length=50), nullable=False))
        batch_op.add_column(sa.Column('fecha', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('hora', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('cantidad', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('valor_maximo', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('provincia', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('localidad', sa.String(length=30), nullable=True))
        batch_op.add_column(sa.Column('tipo', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('observaciones', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('id_technician1', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('id_technician2', sa.Integer(), nullable=True))
        batch_op.alter_column('area',
               existing_type=sa.VARCHAR(length=20),
               type_=sa.String(length=25),
               nullable=True)
        batch_op.drop_column('nombre')
        batch_op.drop_column('apellido')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('NonIonizingRadiation', schema=None) as batch_op:
        batch_op.add_column(sa.Column('apellido', sa.VARCHAR(length=50), nullable=False))
        batch_op.add_column(sa.Column('nombre', sa.VARCHAR(length=50), nullable=False))
        batch_op.alter_column('area',
               existing_type=sa.String(length=25),
               type_=sa.VARCHAR(length=20),
               nullable=False)
        batch_op.drop_column('id_technician2')
        batch_op.drop_column('id_technician1')
        batch_op.drop_column('observaciones')
        batch_op.drop_column('tipo')
        batch_op.drop_column('localidad')
        batch_op.drop_column('provincia')
        batch_op.drop_column('valor_maximo')
        batch_op.drop_column('cantidad')
        batch_op.drop_column('hora')
        batch_op.drop_column('fecha')
        batch_op.drop_column('expediente')

    op.create_table('No',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('nombre', sa.VARCHAR(length=50), nullable=False),
    sa.Column('apellido', sa.VARCHAR(length=50), nullable=False),
    sa.Column('area', sa.VARCHAR(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
